{
 "title": "DSE 855 - SCADA",
 "tags": [
  "dse855",
  "modbus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Link",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_module_link", "legendFormat": "Link" }
   ]
  },
  {
   "title": "Engine Battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_engine_battery_volts", "legendFormat": "Bateria" }
   ]
  },
  {
   "title": "Engine Starts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_engine_starts_total", "legendFormat": "Partidas" }
   ]
  },
  {
   "title": "Engine Hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_engine_hours * 3600", "legendFormat": "Horas" }
   ]
  },
  {
   "title": "Alarm Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_alarm_level", "legendFormat": "Alarm" }
   ]
  },
  {
   "type": "speakyourcode-button-panel",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "speakyourcode-button-panel",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "speakyourcode-button-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  height: 100%;\n  width: 100%;\n\">\n  <h1>POWER METER MAINS</h1>\n</div>"
   }
  },
  {
   "title": "L1 L2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_mains_l1_l2_volts", "legendFormat": "L1 L2" }
   ]
  },
  {
   "title": "L2 L3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_mains_l2_l3_volts", "legendFormat": "L2 L3" }
   ]
  },
  {
   "title": "L3 L1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_mains_l3_l1_volts", "legendFormat": "L3 L1" }
   ]
  },
  {
   "title": "L1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_mains_l1_volts", "legendFormat": "L1" }
   ]
  },
  {
   "title": "L2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_mains_l2_volts", "legendFormat": "L2" }
   ]
  },
  {
   "title": "L3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_mains_l3_volts", "legendFormat": "L3" }
   ]
  },
  {
   "title": "Frequency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_mains_frequency_hz", "legendFormat": "Hz" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  height: 100%;\n  width: 100%;\n\">\n  <h1>ACCUMULETED</h1>\n</div>"
   }
  },
  {
   "title": "kWh",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_accumulated_kwh", "legendFormat": "kWh" }
   ]
  },
  {
   "title": "kVAh",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_accumulated_kvah", "legendFormat": "kVAh" }
   ]
  },
  {
   "title": "kVArh",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dse_accumulated_kvarh", "legendFormat": "kVArh" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  height: 100%;\n  width: 100%;\n\">\n  <h1>Cross analysis</h1>\n</div>"
   }
  },
  {
   "title": "Accumulated Energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "dse_accumulated_kwh", "legendFormat": "Energia ativa acumulada - kWh" },
    {
     "expr": "dse_accumulated_kvah",
     "legendFormat": "Energia aparente acumulada - kVAh"
    },
    {
     "expr": "dse_accumulated_kvarh",
     "legendFormat": "Energia reativa acumulada - kVArh"
    },
    { "expr": "dse_mains_l1_volts", "legendFormat": "Fase L1 (V)" },
    { "expr": "dse_mains_l2_volts", "legendFormat": "Fase L2 (V)" },
    { "expr": "dse_mains_l3_volts", "legendFormat": "Fase L3 (V)" }
   ]
  },
  {
   "title": "Mains L-N",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "dse_mains_l1_volts", "legendFormat": "L1" },
    { "expr": "dse_mains_l2_volts", "legendFormat": "L2" },
    { "expr": "dse_mains_l3_volts", "legendFormat": "L3" }
   ]
  },
  {
   "title": "Mains L-L",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "dse_mains_l1_l2_volts", "legendFormat": "L1-L2" },
    { "expr": "dse_mains_l2_l3_volts", "legendFormat": "L2-L3" },
    { "expr": "dse_mains_l3_l1_volts", "legendFormat": "L3-L1" }
   ]
  }
 ]
}