CREATE TABLE IF NOT EXISTS dse_readings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  collected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sid BIGINT,
  module_model INT,
  module_usbid VARCHAR(64),
  module_link DOUBLE,
  alarm_level DOUBLE,
  battery_v DOUBLE,
  frequency_hz DOUBLE,
  mains_l1_v DOUBLE,
  mains_l2_v DOUBLE,
  mains_l3_v DOUBLE,
  mains_l12_v DOUBLE,
  mains_l23_v DOUBLE,
  mains_l31_v DOUBLE,
  accumulated_kwh DOUBLE,
  accumulated_kvah DOUBLE,
  accumulated_kvarh DOUBLE,
  engine_starts DOUBLE,
  engine_hours_seconds BIGINT,
  engine_hours_text VARCHAR(32),
  raw_payload JSON NOT NULL,
  PRIMARY KEY (id),
  KEY idx_collected_at (collected_at)
);
